jobs:
  test:
    name: Ci
    runs-on: ubuntu-20.04

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Get Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./check/main

name: Build

on:
  schedule:
    - cron: "55 1/3 * * *"
